# /control/verbose 2
# /control/saveHistory
# /run/verbose 2

# /testem/det/setMat Aluminum
# /testem/det/setMat Copper
/testem/det/setMat Tungsten

/testem/det/setLbin 1000 0.001
/testem/det/setRbin 300 0.001
# /run/setCut 0.1 mm

/testem/phys/addPhysics  emstandard_opt0
/run/initialize

# /control/execute vis.mac
/analysis/setFileName Tungsten

/gun/particle e-
/gun/energy 15 MeV

/run/beamOn 15000

